// src/components/Register.tsx
import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import OTPVerification from './OTPVerification';
import './Register.css';

interface RegisterFormData {
    fullName: string;
    email: string;
    password: string;
    confirmPassword: string;
    role: string;
}

interface RegisterResponse {
    message: string;
    success: boolean;
}

const Register: React.FC = () => {
    const [formData, setFormData] = useState<RegisterFormData>({
        fullName: '',
        email: '',
        password: '',
        confirmPassword: '',
        role: 'User'
    });
    const [error, setError] = useState<string>('');
    const [loading, setLoading] = useState<boolean>(false);
    const [showOTPVerification, setShowOTPVerification] = useState<boolean>(false);
    const navigate = useNavigate();

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value
        });
    };

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>): Promise<void> => {
        e.preventDefault();
        setError('');
        setLoading(true);

        // Validate passwords match
        if (formData.password !== formData.confirmPassword) {
            setError('Passwords do not match');
            setLoading(false);
            return;
        }

        // Validate password strength
        if (formData.password.length < 6) {
            setError('Password must be at least 6 characters long');
            setLoading(false);
            return;
        }

        try {
            const requestData = {
                fullName: formData.fullName,
                email: formData.email,
                password: formData.password,
                role: formData.role
            };

            console.log('Sending registration request with data:', requestData);

            const response = await axios.post<RegisterResponse>('https://localhost:7001/api/auth/register', requestData, {
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json'
                }
            });

            console.log('Full response:', response);
            console.log('Response status:', response.status);
            console.log('Response data:', response.data);
            console.log('Response headers:', response.headers);

            // Check if the response is successful
            if (response.status === 200) {
                console.log('Registration successful, showing OTP verification form');
                setShowOTPVerification(true);
            } else {
                console.log('Unexpected response status:', response.status);
                setError('Registration failed. Please try again.');
            }
        } catch (err) {
            console.error('Registration error:', err);
            if (axios.isAxiosError(err)) {
                console.error('Error response:', err.response?.data);
                console.error('Error status:', err.response?.status);
                console.error('Error headers:', err.response?.headers);
                
                if (err.response?.data) {
                    setError(err.response.data.message || 'Registration failed');
                } else {
                    setError(err.message || 'Registration failed. Please try again.');
                }
            } else {
                setError('Registration failed. Please try again.');
            }
        } finally {
            setLoading(false);
        }
    };

    // Debug log for component state
    console.log('Current component state:', {
        showOTPVerification,
        formData,
        error,
        loading
    });

    if (showOTPVerification) {
        console.log('Rendering OTP verification component with email:', formData.email);
        return <OTPVerification email={formData.email} />;
    }

    return (
        <div className="register-container">
            <div className="register-box">
                <h2>Create Account</h2>
                <form onSubmit={handleSubmit}>
                    <div className="form-group">
                        <input
                            type="text"
                            name="fullName"
                            placeholder="Full Name"
                            value={formData.fullName}
                            onChange={handleChange}
                            required
                        />
                    </div>

                    <div className="form-group">
                        <input
                            type="email"
                            name="email"
                            placeholder="Email"
                            value={formData.email}
                            onChange={handleChange}
                            required
                        />
                    </div>

                    <div className="form-group">
                        <input
                            type="password"
                            name="password"
                            placeholder="Password"
                            value={formData.password}
                            onChange={handleChange}
                            required
                            minLength={6}
                        />
                    </div>

                    <div className="form-group">
                        <input
                            type="password"
                            name="confirmPassword"
                            placeholder="Confirm Password"
                            value={formData.confirmPassword}
                            onChange={handleChange}
                            required
                        />
                    </div>

                    {error && <div className="error-message">{error}</div>}

                    <button type="submit" disabled={loading}>
                        {loading ? 'Registering...' : 'Register'}
                    </button>
                </form>

                <div className="login-link">
                    Already have an account? <a href="/login">Login</a>
                </div>
            </div>
        </div>
    );
};

export default Register;

// src/app/components/auth/register/register.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { OtpVerificationComponent } from '../otp-verification/otp-verification.component';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule, OtpVerificationComponent],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent {
  registerForm: FormGroup;
  error: string = '';
  loading: boolean = false;
  showOTPVerification: boolean = false;
  userEmail: string = '';
  private apiUrl = 'https://localhost:44399/api'; // Updated API URL to match the running backend port

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private router: Router
  ) {
    this.registerForm = this.fb.group({
      fullName: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      telephone: ['', [Validators.required, Validators.pattern('^[0-9]{10}$')]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', Validators.required],
      role: ['User']
    }, { validators: this.passwordMatchValidator });
  }

  // Custom Validator for Confirm Password
  passwordMatchValidator(form: FormGroup) {
    const password = form.get('password')?.value;
    const confirmPassword = form.get('confirmPassword')?.value;

    return password === confirmPassword ? null : { mismatch: true };
  }

  // Register method to handle form submission
  register() {
    if (this.registerForm.valid) {
      this.loading = true;
      this.error = '';

      const formData = this.registerForm.value;
      console.log('Register form submitted successfully', formData);

      // Prepare the request data
      const requestData = {
        fullName: formData.fullName,
        email: formData.email,
        password: formData.password,
        passwordHash: formData.password, // The backend will hash this
        role: formData.role || 'User'
      };

      // Make the API call with withCredentials option
      this.http.post(`${this.apiUrl}/auth/register`, requestData, {
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        withCredentials: true
      }).subscribe({
        next: (response: any) => {
          console.log('Registration successful:', response);
          this.userEmail = formData.email;
          this.showOTPVerification = true;
        },
        error: (error) => {
          console.error('Registration error:', error);
          if (error.error) {
            this.error = error.error.message || 'Registration failed';
          } else {
            this.error = 'Registration failed. Please try again.';
          }
        },
        complete: () => {
          this.loading = false;
        }
      });
    } else {
      console.log('Form is invalid');
      this.registerForm.markAllAsTouched(); // Mark all fields as touched to show validation errors
    }
  }
}
<div class="auth-container">
  <div class="auth-register-box">
    <h2>Register</h2>
    <p class="auth-subtitle">Create a new account</p>

    <!-- Show OTP Verification component when registration is successful -->
    <app-otp-verification 
      *ngIf="showOTPVerification" 
      [email]="userEmail">
    </app-otp-verification>

    <!-- Show registration form when not showing OTP verification -->
    <form *ngIf="!showOTPVerification" [formGroup]="registerForm" (ngSubmit)="register()">
      <div class="auth-form-group">
        <label for="fullName">Full Name</label>
        <input 
          type="text" 
          id="fullName" 
          placeholder="Enter your full name" 
          formControlName="fullName" 
          required 
        />
        <div *ngIf="registerForm.get('fullName')?.touched && registerForm.get('fullName')?.invalid" class="auth-error">
          Full name is required
        </div>
      </div>

      <div class="auth-form-group">
        <label for="email">Email Address</label>
        <input 
          type="email" 
          id="email" 
          placeholder="Enter your email" 
          formControlName="email" 
          required 
        />
        <div *ngIf="registerForm.get('email')?.touched && registerForm.get('email')?.invalid" class="auth-error">
          <div *ngIf="registerForm.get('email')?.errors?.['required']">
            Email is required
          </div>
          <div *ngIf="registerForm.get('email')?.errors?.['email']">
            Please enter a valid email address
          </div>
        </div>
      </div>

      <div class="auth-form-group">
        <label for="telephone">Telephone Number</label>
        <input 
          type="tel" 
          id="telephone" 
          placeholder="Enter your 10-digit telephone number" 
          formControlName="telephone" 
          required 
          pattern="^[0-9]{10}$"
          maxlength="10"
        />
        <div *ngIf="registerForm.get('telephone')?.touched && registerForm.get('telephone')?.invalid" class="auth-error">
          <div *ngIf="registerForm.get('telephone')?.errors?.['required']">
            Telephone number is required
          </div>
          <div *ngIf="registerForm.get('telephone')?.errors?.['pattern']">
            Please enter a valid 10-digit phone number
          </div>
        </div>
      </div>

      <div class="auth-form-group">
        <label for="password">Password</label>
        <input 
          type="password" 
          id="password" 
          placeholder="Enter your password" 
          formControlName="password" 
          required 
        />
        <div *ngIf="registerForm.get('password')?.touched && registerForm.get('password')?.invalid" class="auth-error">
          <div *ngIf="registerForm.get('password')?.errors?.['required']">
            Password is required
          </div>
          <div *ngIf="registerForm.get('password')?.errors?.['minlength']">
            Password must be at least 6 characters long
          </div>
        </div>
      </div>

      <div class="auth-form-group">
        <label for="confirmPassword">Confirm Password</label>
        <input 
          type="password" 
          id="confirmPassword" 
          placeholder="Confirm your password" 
          formControlName="confirmPassword" 
          required 
        />
        <div *ngIf="registerForm.get('confirmPassword')?.touched && registerForm.get('confirmPassword')?.invalid" class="auth-error">
          <div *ngIf="registerForm.get('confirmPassword')?.errors?.['required']">
            Please confirm your password
          </div>
        </div>
        <div *ngIf="registerForm.errors?.['mismatch'] && registerForm.get('confirmPassword')?.touched" class="auth-error">
          Passwords do not match
        </div>
      </div>

      <!-- Show error message if any -->
      <div *ngIf="error" class="auth-error-message">
        {{ error }}
      </div>

      <button 
        type="submit" 
        class="auth-button" 
        [disabled]="registerForm.invalid || registerForm.pristine || loading">
        {{ loading ? 'Registering...' : 'Register' }}
      </button>

      <div class="auth-login-link">
        Already have an account? 
        <a routerLink="/auth/login">Sign in</a>
      </div>
    </form>
  </div>
</div>
